### ISSUE TITLE
Geliştirme Yapmanın Yolları

### ISSUE THREAD

**Issue by alperen** [naynco/nayn.wordpress#6]
Bir kişinin bu repository üzerinde geliştirme yapabilmesi için aşağıdaki sorulara cevap bulabilmesi gerekir.

- Proje local ortama kurulduktan sonra nasıl çalıştırılacak?
- Projenin image, sass ve js kodları nasıl bir işlemden geçirilerek `assets` klasörüne taşınacak?
- Pull Request hangi branch'e atılacak, nasıl birleştirilecek?
- Commit yazma kuralları nasıl olacak?

**Comment by hmert** [comment]
@alperen Selam,

Standart bir WordPress teması olduğumuz için bunları açıklamayı düşünmemiştim. Readme dosyasında güncellemeler yaptım. Eğer senin için yeterli gelmezse yeniden issue açabilirsin. 

Geliştirme yapmak istediğin bir konu varsa sana geliştirme ortamı oluşturur bu sayede eksiğim olursa tamamlarım.
